#!/bin/bash
echo "=== SMITH'S FREIGHT HUB - FULL FEATURE CHECK ==="
echo ""

echo "--- KEY FILES ---"
files=(
  "app/api/drivers/route.js"
  "app/admin/page.js"
  "app/admin/drivers/new/page.js"
  "app/admin/drivers/[id]/page.js"
  "app/admin/reports/settlements/page.js"
  "app/admin/reports/tickets/page.js"
  "app/admin/reports/timesheets/page.js"
  "app/admin/reports/maintenance/page.js"
  "app/admin/ticket/[id]/page.js"
  "app/admin/maintenance/[id]/page.js"
  "app/admin/compliance/page.js"
  "app/admin/messages/page.js"
  "app/driver/page.js"
  "app/driver/ticket/new/page.js"
  "app/driver/ticket/[id]/page.js"
  "app/driver/timesheet/page.js"
  "app/driver/maintenance/page.js"
  "app/driver/compliance/page.js"
  "app/driver/messages/page.js"
  "app/login/page.js"
  "lib/supabase.js"
  "lib/supabase-admin.js"
  ".env.local"
)
for f in "${files[@]}"; do
  [ -f "$f" ] && echo "✅ $f" || echo "❌ MISSING: $f"
done

echo ""
echo "--- ADMIN FEATURES ---"
grep -q "Add New Driver" app/admin/page.js && echo "✅ Add new driver" || echo "❌ Add new driver"
grep -q "reports" app/admin/page.js && echo "✅ Reports tab" || echo "❌ Reports tab"
grep -q "timesheets" app/admin/page.js && echo "✅ Timesheets tab" || echo "❌ Timesheets tab"
grep -q "maintenance" app/admin/page.js && echo "✅ Maintenance tab" || echo "❌ Maintenance tab"
grep -q "ticketFilter" app/admin/page.js && echo "✅ Ticket filtering" || echo "❌ Ticket filtering"
grep -q "search" app/admin/page.js && echo "✅ Ticket search" || echo "❌ Ticket search"
grep -q "handleLogout" app/admin/page.js && echo "✅ Admin logout" || echo "❌ Admin logout"

echo ""
echo "--- DRIVER FEATURES ---"
grep -q "ticket" app/driver/page.js && echo "✅ Driver ticket access" || echo "❌ Driver ticket access"
grep -q "timesheet" app/driver/page.js && echo "✅ Driver timesheet access" || echo "❌ Driver timesheet access"
grep -q "maintenance" app/driver/page.js && echo "✅ Driver maintenance access" || echo "❌ Driver maintenance access"
grep -q "compliance" app/driver/page.js && echo "✅ Driver compliance access" || echo "❌ Driver compliance access"
grep -q "messages" app/driver/page.js && echo "✅ Driver messages access" || echo "❌ Driver messages access"

echo ""
echo "--- TICKETS ---"
grep -q "boxes" app/driver/ticket/new/page.js && echo "✅ Box/weight entry on tickets" || echo "❌ Box/weight entry"
grep -q "location_loaded" app/driver/ticket/new/page.js && echo "✅ Location field" || echo "❌ Location field"
grep -q "load_id" app/driver/ticket/new/page.js && echo "✅ Load ID field" || echo "❌ Load ID field"
grep -q "approved\|rejected" app/admin/ticket/[id]/page.js && echo "✅ Admin approve/reject tickets" || echo "❌ Approve/reject"

echo ""
echo "--- TIMESHEETS ---"
grep -q "state_miles" app/driver/timesheet/page.js && echo "✅ State miles tracking" || echo "❌ State miles tracking"
grep -q "start_time\|end_time" app/driver/timesheet/page.js && echo "✅ Start/end time logging" || echo "❌ Time logging"

echo ""
echo "--- SETTLEMENTS & REPORTS ---"
grep -q "fetch(\"/api/drivers\")" app/admin/reports/settlements/page.js && echo "✅ Driver dropdown loads correctly" || echo "❌ Driver dropdown"
grep -q "claude\|anthropic\|AI\|ai" app/admin/reports/settlements/page.js && echo "✅ AI settlement generation" || echo "❌ AI settlement generation"
grep -q "exportCSV\|csv" app/admin/reports/settlements/page.js && echo "✅ CSV export" || echo "❌ CSV export"
grep -q "stateMiles\|state_miles" app/admin/reports/settlements/page.js && echo "✅ State miles in settlement" || echo "❌ State miles in settlement"

echo ""
echo "--- MESSAGING ---"
grep -q "message\|Message" app/admin/messages/page.js && echo "✅ Admin messaging" || echo "❌ Admin messaging"
grep -q "message\|Message" app/driver/messages/page.js && echo "✅ Driver messaging" || echo "❌ Driver messaging"

echo ""
echo "--- AUTH & SECURITY ---"
grep -q "supabaseAdmin" app/api/drivers/route.js && echo "✅ Driver API uses service role (bypasses RLS)" || echo "❌ RLS bypass"
grep -q "admin_auth" app/admin/page.js && echo "✅ Admin auth check" || echo "❌ Admin auth check"
grep -q "password\|Password" app/admin/drivers/new/page.js && echo "✅ Password creation for drivers" || echo "❌ Password creation"
grep -q "generatePassword\|Generate" app/admin/drivers/new/page.js && echo "✅ Auto-generate password" || echo "❌ Auto-generate password"

echo ""
echo "=== DONE ==="
